substitutions:
  device_name: "huawei_r4875g1"

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32dev

external_components:
  - source:
      type: local
      path: esphome/components/huawei_r4875g1

# CAN总线配置
canbus:
  - platform: esp32_can
    id: can_bus1
    tx_pin: GPIO5
    rx_pin: GPIO4
    bit_rate: 125kbps
    can_id: 0

# 华为整流器配置
huawei_r4875g1:
  id: huawei1
  canbus_id: can_bus1
  update_interval: 1s
  
  # 传感器校准
  sensors:
    input_voltage:
      multiplier: 1.012
      offset: -0.15
    output_voltage:
      multiplier: 1.025
      offset: 0.2
    input_current:
      multiplier: 1.03
      offset: -0.05
    output_current:
      multiplier: 0.985
      offset: 0.1
  
  # 高压模式配置
  voltage_limits:
    min: 41.5
    max: 100.0  # 最高100V
  current_limits:
    min: 0.0
    max: 90.5

# 传感器定义
sensor:
  - platform: huawei_r4875g1
    type: input_voltage
    name: "Input Voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 1
    id: input_voltage
    
  - platform: huawei_r4875g1
    type: output_voltage
    name: "Output Voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 2
    id: output_voltage

  - platform: huawei_r4875g1
    type: output_current
    name: "Output Current"
    unit_of_measurement: "A"
    accuracy_decimals: 2
    id: output_current

  - platform: huawei_r4875g1
    type: output_power
    name: "Output Power"
    unit_of_measurement: "W"
    accuracy_decimals: 1
    id: output_power

  - platform: huawei_r4875g1
    type: temperature
    name: "Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    id: temperature

# 状态指示
binary_sensor:
  - platform: huawei_r4875g1
    name: "Operational Status"
    id: operational_status

# API服务
api:
  services:
    - service: set_output_voltage
      variables:
        voltage: float
      then:
        - huawei_r4875g1.set_voltage:
            id: huawei1
            voltage: !lambda 'return voltage;'

    - service: set_current_limit
      variables:
        current: float
      then:
        - huawei_r4875g1.set_current:
            id: huawei1
            current: !lambda 'return current;'

    - service: enable_unit
      then:
        - huawei_r4875g1.enable:
            id: huawei1

    - service: disable_unit
      then:
        - huawei_r4875g1.disable:
            id: huawei1

# 可选：日志配置
logger:
  baud_rate: 0